package dev.aisentinel.core.scoring.artifact;

/**
 * Structured reason codes for candidate scorer/model artifact validation failures.
 * <p>
 * Validation failure is an engineering/configuration condition.
 * {@code INFRASTRUCTURE FAILURE != ATTACK}.
 */
public enum ScorerArtifactValidationIssueCode {
    INVALID_DESCRIPTOR_SCHEMA,
    MISSING_OR_BLANK_SCORER_ID,
    INVALID_SCORER_ID,
    MISSING_OR_BLANK_SCORER_VERSION,
    INVALID_SCORER_VERSION,
    MISSING_OR_BLANK_ARTIFACT_ID,
    INVALID_ARTIFACT_ID,
    MISSING_OR_BLANK_ARTIFACT_FORMAT,
    INVALID_ARTIFACT_FORMAT,
    MISSING_OR_BLANK_SCORER_TYPE,
    INVALID_SCORER_TYPE,
    MISSING_ARTIFACT_DIGEST,
    UNSUPPORTED_DIGEST_ALGORITHM,
    MALFORMED_DIGEST,
    UNSUPPORTED_FEATURE_SCHEMA,
    EMPTY_REQUIRED_FEATURES,
    BLANK_REQUIRED_FEATURE,
    DUPLICATE_REQUIRED_FEATURE,
    UNKNOWN_REQUIRED_FEATURE,
    FEATURE_DIMENSION_MISMATCH,
    INCOMPATIBLE_FEATURE_ORDER,
    INCOMPATIBLE_OUTPUT_RANGE,
    CONTRADICTORY_CAPABILITY_CLAIM
}
