#!/usr/bin/env python3
"""Verify reference-performance baseline selection-analysis evidence integrity.

Checks that the tracked selection-analysis artifact bytes match the SHA-256
recorded in docs/performance/reference-baseline.json.

Optionally verifies local gitignored raw capture artifacts (capture notes and
per-run jmh.json / manifest.json) when they are present. Absence of those
local files is not drift: capture may recreate them, but the selection analysis
is historical evidence and is not regenerated by capture.

Does not recapture benchmarks, alter metrics, or rewrite historical digests.

Exit codes:
  0 — verified
  1 — verification failure
  2 — usage error
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_baseline(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError("baseline root must be a JSON object")
    raw = data.get("rawEvidence")
    if not isinstance(raw, dict):
        raise ValueError("baseline.rawEvidence must be an object")
    return data


def require_hex_sha256(value: object, label: str) -> str:
    if not isinstance(value, str) or len(value) != 64 or any(
        c not in "0123456789abcdef" for c in value
    ):
        raise ValueError(f"{label} must be 64 lowercase hex characters")
    return value


def resolve_under_root(root: Path, rel: str, label: str) -> Path:
    candidate = (root / rel).resolve()
    root_resolved = root.resolve()
    if root_resolved not in candidate.parents and candidate != root_resolved:
        raise ValueError(f"{label} escapes repository root: {rel}")
    return candidate


def verify(
    root: Path,
    baseline_path: Path,
    *,
    require_local_raw: bool = False,
) -> int:
    try:
        baseline = load_baseline(baseline_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: cannot read baseline {baseline_path}: {exc}", file=sys.stderr)
        return 1

    raw = baseline["rawEvidence"]
    try:
        analysis_rel = raw.get("analysisFile")
        if not isinstance(analysis_rel, str) or not analysis_rel:
            raise ValueError("rawEvidence.analysisFile must be a non-empty string")
        expected_analysis = require_hex_sha256(raw.get("analysisSha256"), "analysisSha256")
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    try:
        analysis_path = resolve_under_root(root, analysis_rel, "analysisFile")
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if not analysis_path.is_file():
        print(f"ERROR: tracked selection analysis missing: {analysis_rel}", file=sys.stderr)
        return 1

    actual_analysis = sha256_file(analysis_path)
    if actual_analysis != expected_analysis:
        print("DRIFT: selection analysis SHA-256 mismatch", file=sys.stderr)
        print(f"  file:     {analysis_rel}", file=sys.stderr)
        print(f"  expected: {expected_analysis}", file=sys.stderr)
        print(f"  actual:   {actual_analysis}", file=sys.stderr)
        return 1

    print(f"MATCH selection analysis {analysis_rel}")
    print(f"  sha256={actual_analysis}")

    optional_checks: list[tuple[str, str, str]] = []
    notes_sha = raw.get("captureNotesSha256")
    if isinstance(notes_sha, str):
        optional_checks.append(
            (
                "capture notes",
                "ai-sentinel-benchmark/results/reference-capture/capture-notes.txt",
                notes_sha,
            )
        )
    for run in raw.get("runArtifacts") or []:
        if not isinstance(run, dict):
            continue
        run_id = run.get("run")
        jmh = run.get("jmhFile")
        jmh_sha = run.get("jmhSha256")
        man = run.get("manifestFile")
        man_sha = run.get("manifestSha256")
        if isinstance(jmh, str) and isinstance(jmh_sha, str):
            optional_checks.append((f"run-{run_id} jmh", jmh, jmh_sha))
        if isinstance(man, str) and isinstance(man_sha, str):
            optional_checks.append((f"run-{run_id} manifest", man, man_sha))

    missing = 0
    matched = 0
    for label, rel, expected in optional_checks:
        try:
            path = resolve_under_root(root, rel, label)
        except ValueError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1
        if not path.is_file():
            missing += 1
            if require_local_raw:
                print(f"ERROR: required local raw artifact missing: {rel}", file=sys.stderr)
                return 1
            print(f"ABSENT optional local raw artifact ({label}): {rel}")
            continue
        try:
            expected_hex = require_hex_sha256(expected, f"{label} sha")
        except ValueError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1
        actual = sha256_file(path)
        if actual != expected_hex:
            print(f"DRIFT: {label} SHA-256 mismatch", file=sys.stderr)
            print(f"  file:     {rel}", file=sys.stderr)
            print(f"  expected: {expected_hex}", file=sys.stderr)
            print(f"  actual:   {actual}", file=sys.stderr)
            return 1
        matched += 1
        print(f"MATCH optional local raw artifact ({label})")

    print(
        "reference performance baseline evidence verification PASS "
        f"(selection analysis required; optional local raw matched={matched} absent={missing})"
    )
    return 0


def self_test(root: Path, baseline_path: Path) -> int:
    """Prove meaningful selection-analysis mutation fails; restore temp copy only."""
    baseline = load_baseline(baseline_path)
    raw = baseline["rawEvidence"]
    analysis_rel = raw["analysisFile"]
    analysis_path = root / analysis_rel
    if not analysis_path.is_file():
        print(f"ERROR: self-test requires tracked analysis at {analysis_rel}", file=sys.stderr)
        return 1

    # Happy path
    if verify(root, baseline_path) != 0:
        print("ERROR: self-test happy path failed", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="aisentinel-perf-baseline-") as tmp:
        tmp_root = Path(tmp)
        # Minimal repo layout with mutated analysis and copied baseline
        tracked_dir = tmp_root / "docs" / "performance"
        tracked_dir.mkdir(parents=True)
        mutated = tracked_dir / Path(analysis_rel).name
        original = analysis_path.read_bytes()
        # Meaningful semantic mutation: change a selected metric value in JSON
        obj = json.loads(original.decode("utf-8"))
        if not obj.get("results"):
            print("ERROR: self-test analysis has no results", file=sys.stderr)
            return 1
        obj["results"][0]["mean"] = float(obj["results"][0]["mean"]) + 1.0
        mutated.write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8")

        baseline_copy = tracked_dir / "reference-baseline.json"
        # Point analysisFile at the mutated relative path under tmp root
        baseline_obj = json.loads(baseline_path.read_text(encoding="utf-8"))
        baseline_obj["rawEvidence"]["analysisFile"] = str(
            Path("docs/performance") / mutated.name
        )
        baseline_copy.write_text(json.dumps(baseline_obj, indent=2) + "\n", encoding="utf-8")

        import contextlib
        import io

        buf = io.StringIO()
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
            rc = verify(tmp_root, baseline_copy)
        if rc == 0:
            print("ERROR: self-test expected DRIFT on mutated mean, got PASS", file=sys.stderr)
            return 1
        if "DRIFT: selection analysis SHA-256 mismatch" not in buf.getvalue():
            print("ERROR: self-test did not report selection-analysis drift", file=sys.stderr)
            print(buf.getvalue(), file=sys.stderr)
            return 1
        print("SELF-TEST deliberate semantic drift correctly FAILED verification")

    # Volatile-field case: none — selection analysis has no approved volatile fields.
    print("SELF-TEST volatile-field case: NOT APPLICABLE (no approved volatile fields)")
    print("SELF-TEST PASS")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Verify reference-performance baseline selection-analysis evidence"
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Repository root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--baseline",
        type=Path,
        default=None,
        help="Path to reference-baseline.json",
    )
    parser.add_argument(
        "--require-local-raw",
        action="store_true",
        help="Fail if gitignored local raw capture artifacts are absent",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="Run deliberate-drift regression checks using temporary copies only",
    )
    args = parser.parse_args(argv)

    script_root = Path(__file__).resolve().parent.parent
    root = (args.root or script_root).resolve()
    baseline_path = (
        args.baseline.resolve()
        if args.baseline
        else (root / "docs/performance/reference-baseline.json")
    )

    if args.self_test:
        return self_test(root, baseline_path)
    return verify(root, baseline_path, require_local_raw=args.require_local_raw)


if __name__ == "__main__":
    sys.exit(main())
